### ISSUE TITLE
Completed - In-class exercise CSS flex 

### ISSUE THREAD

**Issue by ongmin** [ongmin/wdi-sg-playground#1]
Hello @sevresbabylone @cbas,

here's our work. :) Inspired by: https://news.ycombinator.com/news
Thanks!

Cheers,
Min and Jeremly (@wytanj)

**Comment by cbas** [comment]
:sparkles: Great! :sparkles: 

Feedback:
- Avoid non-semantic elements like `#breaker` and `#breakerline` and use paddings/margins/borders instead.
- Don't make the `|` pipes part of the `<a>` content. Place them in between, or, better yet, inject them using CSS using a `border` or the `content` property on a `:before` or `:after` pseudo-element.
- Use an `<ol>` to add numbering to the list.
- Use semantic, meaningful, descriptive names for classes instead of `container1`.

**Comment by ongmin** [comment]
Thanks alot! :smile: 
:chocolate_bar:
